name: Opencode

on:
  push:
    branches: ["main"]
    tags: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    if: github.repository_owner == 'robert-koch-institut'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Push main branch
        run: |
          git remote add opencode https://RKIMetadataExchange:${{ secrets.MEX_OPENCODE_TOKEN }}@gitlab.opencode.de/robert-koch-institut/mex/mex-common.git
          git push opencode -f
          git push opencode -f --tags
