name: Renovate

on:
  push:
    branches: ["main"]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "14 3 * * 1-5"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Run renovatebot
        uses: renovatebot/github-action@v40
        env:
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.SIGNING_KEY }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.WORKFLOW_TOKEN }}
