name: Renovate

on:
  push:
    branches: ["main"]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "14 3 * * 1-5"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run renovatebot
        uses: renovatebot/github-action@v40.1.9
        env:
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          RENOVATE_REPOSITORIES: "robert-koch-institut/mex-common"
        with:
          configurationFile: renovate.json
          token: ${{ secrets.WORKFLOW_TOKEN }}
