name: Renovate

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "14 3 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Run renovatebot
        uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        env:
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.MEX_PLAIN_SIGNING_KEY }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.MEX_RENOVATE_TOKEN }}
