name: Renovate

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "14 3 * * 1-5"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run renovatebot
        uses: renovatebot/github-action@v40.1.7
        with:
          configurationFile: renovate.json
          token: ${{ secrets.WORKFLOW_TOKEN }}
