name: Reviewing

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add-assignee:
    name: Add assignee
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Resolve assignee
        id: resolve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          user_name="${{ github.event.pull_request.user.login }}"
          user_type=$(gh api "users/${user_name}" --jq ".type")
          echo $user_name is a $user_type
          if [[ "$user_type" != "User" ]]; then
            user_name="RKIMetadataExchange"
            echo using $user_name instead
          fi
          echo "user_name=${user_name}" >> "$GITHUB_OUTPUT"

      - name: Add assignee
        if: ${{ !github.event.pull_request.assignee.login }}
        env:
          GH_TOKEN: ${{ secrets.MEX_COLLAB_WRITE_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
          --add-assignee "${{ steps.resolve.outputs.user_name }}"

  check-changelog:
    name: Check changelog
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Check for CHANGELOG.md changes
        run: |
          if [ "${{ github.actor }}" = "RKIMetadataExchange" ]; then
            echo "Actor is 'RKIMetadataExchange'. Skipping changelog check."
            exit 0;
          fi

          if git diff --quiet "origin/${{ github.base_ref }}"...HEAD -- "CHANGELOG.md"; then
            echo "Error: The CHANGELOG.md has not been modified."
            echo "Please add your changes to CHANGELOG.md before merging."
            exit 1
          else
            echo "CHANGELOG.md has been modified."
            exit 0
          fi
