test_john = {
    "orcid-identifier": {
        "uri": "https://orcid.org/0000-0002-1825-0097",
        "path": "0000-0002-1825-0097",
        "host": "orcid.org",
    },
    "person": {
        "last-modified-date": {"value": 1494016313820},
        "name": {
            "created-date": {"value": 1460757617078},
            "last-modified-date": {"value": 1504850007188},
            "given-names": {"value": "Josiah"},
            "family-name": {"value": "Carberry"},
            "credit-name": None,
            "source": None,
            "visibility": "public",
            "path": "0000-0002-1825-0097",
        },
        "emails": {
            "last-modified-date": None,
            "email": [],
            "path": "/0000-0002-1825-0097/email",
        },
    },
}

record_vyvy = {
    "orcid-identifier": {
        "uri": "https://orcid.org/0009-0004-3041-5706",
        "path": "0009-0004-3041-5706",
        "host": "orcid.org",
    },
    "preferences": {"locale": "en"},
    "history": {
        "creation-method": "DIRECT",
        "completion-date": None,
        "submission-date": {"value": 1729001669889},
        "last-modified-date": {"value": 1730814244260},
        "claimed": True,
        "source": None,
        "deactivation-date": None,
        "verified-email": True,
        "verified-primary-email": True,
    },
    "person": {
        "last-modified-date": None,
        "name": {
            "created-date": {"value": 1729001670037},
            "last-modified-date": {"value": 1730814244255},
            "given-names": {"value": "VyVy"},
            "family-name": {"value": "Tran Ngoc"},
            "credit-name": None,
            "source": None,
            "visibility": "public",
            "path": "0009-0004-3041-5706",
        },
        "other-names": {
            "last-modified-date": None,
            "other-name": [],
            "path": "/0009-0004-3041-5706/other-names",
        },
        "biography": None,
        "researcher-urls": {
            "last-modified-date": None,
            "researcher-url": [],
            "path": "/0009-0004-3041-5706/researcher-urls",
        },
        "emails": {
            "last-modified-date": None,
            "email": [],
            "path": "/0009-0004-3041-5706/email",
        },
        "addresses": {
            "last-modified-date": None,
            "address": [],
            "path": "/0009-0004-3041-5706/address",
        },
        "keywords": {
            "last-modified-date": None,
            "keyword": [],
            "path": "/0009-0004-3041-5706/keywords",
        },
        "external-identifiers": {
            "last-modified-date": None,
            "external-identifier": [],
            "path": "/0009-0004-3041-5706/external-identifiers",
        },
        "path": "/0009-0004-3041-5706/person",
    },
    "activities-summary": {
        "last-modified-date": None,
        "distinctions": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/distinctions",
        },
        "educations": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/educations",
        },
        "employments": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/employments",
        },
        "fundings": {
            "last-modified-date": None,
            "group": [],
            "path": "/0009-0004-3041-5706/fundings",
        },
        "invited-positions": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/invited-positions",
        },
        "memberships": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/memberships",
        },
        "peer-reviews": {
            "last-modified-date": None,
            "group": [],
            "path": "/0009-0004-3041-5706/peer-reviews",
        },
        "qualifications": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/qualifications",
        },
        "research-resources": {
            "last-modified-date": None,
            "group": [],
            "path": "/0009-0004-3041-5706/research-resources",
        },
        "services": {
            "last-modified-date": None,
            "affiliation-group": [],
            "path": "/0009-0004-3041-5706/services",
        },
        "works": {
            "last-modified-date": None,
            "group": [],
            "path": "/0009-0004-3041-5706/works",
        },
        "path": "/0009-0004-3041-5706/activities",
    },
    "path": "/0009-0004-3041-5706",
}

seelig_stefanie = {
    "orcid-identifier": {
        "uri": "https://orcid.org/0000-0002-1825-0097",
        "path": "0000-0002-1825-0097",
        "host": "orcid.org",
    },
    "preferences": {"locale": "en"},
    "history": {
        "creation-method": "WEBSITE",
        "completion-date": {"value": 1352727077585},
        "submission-date": {"value": 1352723476658},
        "last-modified-date": {"value": 1725087603643},
        "claimed": True,
        "source": None,
        "deactivation-date": None,
        "verified-email": True,
        "verified-primary-email": True,
    },
    "person": {
        "last-modified-date": {"value": 1494016313820},
        "name": {
            "created-date": {"value": 1460757617078},
            "last-modified-date": {"value": 1504850007188},
            "given-names": {"value": "Josiah"},
            "family-name": {"value": "Carberry"},
            "credit-name": None,
            "source": None,
            "visibility": "public",
            "path": "0000-0002-1825-0097",
        },
        "other-names": {
            "last-modified-date": {"value": 1462157547720},
            "other-name": [
                {
                    "created-date": {"value": 1462157351411},
                    "last-modified-date": {"value": 1462157547720},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "content": "Josiah Stinkney Carberry",
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/other-names/732317",
                    "put-code": 732317,
                    "display-index": 3,
                },
                {
                    "created-date": {"value": 1446663146889},
                    "last-modified-date": {"value": 1462157547720},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "content": "J. Carberry",
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/other-names/565981",
                    "put-code": 565981,
                    "display-index": 2,
                },
                {
                    "created-date": {"value": 1462157351418},
                    "last-modified-date": {"value": 1462157547720},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "content": "J. S. Carberry",
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/other-names/732318",
                    "put-code": 732318,
                    "display-index": 1,
                },
            ],
            "path": "/0000-0002-1825-0097/other-names",
        },
        "biography": {
            "created-date": {"value": 1460757617080},
            "last-modified-date": {"value": 1460757617080},
            "content": 'Josiah Carberry is a fictitious person. This account is used as a demonstration account by ORCID, CrossRef and others who wish to demonstrate the interaction of ORCID with other scholarly communication systems without having to use a real-person\'s account.\r\n\r\nJosiah Stinkney Carberry is a fictional professor, created as a joke in 1929. He is said to still teach at Brown University, and to be known for his work in "psychoceramics", the supposed study of "cracked pots". See his Wikipedia entry for more details.',
            "visibility": "public",
            "path": "/0000-0002-1825-0097/biography",
        },
        "researcher-urls": {
            "last-modified-date": {"value": 1462157645967},
            "researcher-url": [
                {
                    "created-date": {"value": 1446663146890},
                    "last-modified-date": {"value": 1462157645967},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "url-name": "Brown University Page",
                    "url": {"value": "http://library.brown.edu/about/hay/carberry.php"},
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/researcher-urls/568395",
                    "put-code": 568395,
                    "display-index": 2,
                },
                {
                    "created-date": {"value": 1446663146889},
                    "last-modified-date": {"value": 1462157645967},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "url-name": "Wikipedia Entry",
                    "url": {"value": "http://en.wikipedia.org/wiki/Josiah_Carberry"},
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/researcher-urls/568394",
                    "put-code": 568394,
                    "display-index": 1,
                },
            ],
            "path": "/0000-0002-1825-0097/researcher-urls",
        },
        "emails": {
            "last-modified-date": None,
            "email": [],
            "path": "/0000-0002-1825-0097/email",
        },
        "addresses": {
            "last-modified-date": None,
            "address": [],
            "path": "/0000-0002-1825-0097/address",
        },
        "keywords": {
            "last-modified-date": {"value": 1462157635636},
            "keyword": [
                {
                    "created-date": {"value": 1462157617244},
                    "last-modified-date": {"value": 1462157635636},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "content": "psychoceramics",
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/keywords/434187",
                    "put-code": 434187,
                    "display-index": 3,
                },
                {
                    "created-date": {"value": 1462157414545},
                    "last-modified-date": {"value": 1462157635636},
                    "source": {
                        "source-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "source-client-id": None,
                        "source-name": {"value": "Josiah Carberry"},
                        "assertion-origin-orcid": None,
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": None,
                    },
                    "content": "ionian philology",
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/keywords/434184",
                    "put-code": 434184,
                    "display-index": 2,
                },
            ],
            "path": "/0000-0002-1825-0097/keywords",
        },
        "external-identifiers": {
            "last-modified-date": {"value": 1494016313820},
            "external-identifier": [
                {
                    "created-date": {"value": 1494016313820},
                    "last-modified-date": {"value": 1494016313820},
                    "source": {
                        "source-orcid": None,
                        "source-client-id": {
                            "uri": "https://orcid.org/client/0000-0002-5982-8983",
                            "path": "0000-0002-5982-8983",
                            "host": "orcid.org",
                        },
                        "source-name": {"value": "Scopus - Elsevier"},
                        "assertion-origin-orcid": {
                            "uri": "https://orcid.org/0000-0002-1825-0097",
                            "path": "0000-0002-1825-0097",
                            "host": "orcid.org",
                        },
                        "assertion-origin-client-id": None,
                        "assertion-origin-name": {"value": "Josiah Carberry"},
                    },
                    "external-id-type": "Scopus Author ID",
                    "external-id-value": "7007156898",
                    "external-id-url": {
                        "value": "http://www.scopus.com/inward/authorDetails.url?authorID=7007156898&partnerID=MN8TOARS"
                    },
                    "external-id-relationship": "self",
                    "visibility": "public",
                    "path": "/0000-0002-1825-0097/external-identifiers/698979",
                    "put-code": 698979,
                    "display-index": 0,
                }
            ],
            "path": "/0000-0002-1825-0097/external-identifiers",
        },
        "path": "/0000-0002-1825-0097/person",
    },
    "path": "/0000-0002-1825-0097",
}
